Create community_guidelines.md
OperationCode/START_HERE pull request #61
Opened 2020-08-31 20:12 UTC by hollomancer

2020-08-31 22:00 UTC, andy5995 requested changes
Looks very good. I just suggested a few minor changes.

2020-08-31 22:00 UTC, andy5995 commented on community_guidelines.md
> +**ACT PROFESSIONAL**
```suggestion
**ACT PROFESSIONALLY**
```

2020-08-31 22:00 UTC, andy5995 commented on community_guidelines.md
> +* If we see members acting unprofessional, moderators reserve the right to remove them from the community.
```suggestion
* If we see members acting unprofessionally, moderators reserve the right to remove them from the community.
```

I think an adverb may be more appropriate here (-ly)

2020-08-31 22:00 UTC, andy5995 commented on community_guidelines.md
> +* Being a part of the Operation Code community is a privilege - not a right. Failure to adhere to the community guidelines can result in your messages being removed (either automatically by our bot,
```suggestion
* Being a part of the Operation Code community is a privilege - not a right. Failure to adhere to the community guidelines can result in your messages being removed (either automatically by our bot, or at an administrator’s discretion). Repeated violation will result in loss of access to the community. You are also expected to follow our Code of Conduct [ here](https://github.com/OperationCode/operationcode_docs/blob/master/community/code_of_conduct.md).
```

2020-09-01 00:43 UTC, hollomancer commented on community_guidelines.md
> +* Being a part of the Operation Code community is a privilege - not a right. Failure to adhere to the community guidelines can result in your messages being removed (either automatically by our bot,
Thank you!

2020-09-01 03:19 UTC, merged